name: flutter_talkie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  go_router: ^14.2.7
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.2
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
