name: talkie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  go_router: ^14.2.7
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.2
  socket_io_client: ^2.0.3+1
  timeago: ^3.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F7F7FC"
  color_dark: "#0F1828"

  image: assets/app/splash.png
  image_dark: assets/app/splash.png

  android_12:
    image: assets/app/splash.png
    image_dark: assets/app/splash.png
    color: "#F7F7FC"
    color_dark: "#0F1828"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/icons/tabs/
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Black.ttf
          weight: 800
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish/Mulish-ExtraLight.ttf
          weight: 200
